### PR TITLE
Improvements for v2.0.0

### LINKED ISSUE #2: Eingabe des MQTT Topics
Wäre es möglich, das MQTT Topic als konfigurierbaren Wert in die AP-Mode Konfigurationsseite mit aufzunehmen?
Vielleicht mit dem Namen des MQTT Clients als möglicher Variable? So ähnlich wie das zum Beispiel Tasmota macht.

### PR DESCRIPTION
**Pull request by loelkes**
# Fixes
* 564f17c Fixes the issue where the MQTT only starts if the Broker IP is 127.0.0.1
* c797c15 Use the available credentials for MQTT
# New features
* 8bdb805 Add a volume parameter for the buzzer
* f7c528c Add possibility to enable a debug log
* 3887445 Allow setting a default SSID and passwort without using the webinterface
# Miscellaneous
* 69cae5a daeff30 9b6d655 Refactor, improve code aesthetics
* 3ad5430 c58c5d1 b297c5b Update documentation and logging verbosity

Includes the PR #6 from @reibuehl and fixes #2

### CODE REVIEW

**Comment by loelkes** [comment]
Since the changes in `Config.h` such as the renaming of constants following a more consistent logic involve incompatible API changes I suggest incrementing the major version. This would lead to v2.0.0

**Comment by mariolukas** [comment]
Thank you. I will do a release 2.0.0

**Comment by mariolukas** [comment]
Forgot the merge before closing this PR.

**Comment by loelkes** [comment]
@mariolukas This was not merged? The new release does not contain any of this?

**Comment by mariolukas** [comment]
You are right, something went wrong. Just fixed it.

**Pull request merged**
